### ISSUE TITLE
Dual motor self-squarring

### ISSUE THREAD

**Issue by akzmonster** [gnea/grbl-Mega#110] opened 2019-08-27 20:30 UTC
I was reading through the 328P version of dual motor and noticed that it can only utilize x OR y dual axis support. Could this be x AND y for the mega? Thanks so much!

Line 644 in config
#define DUAL_AXIS_SELECT  X_AXIS  // Must be either X_AXIS or Y_AXIS

**Comment by fra589** [comment] 2019-08-28 07:09
My grbl-Mega-5X version can do it : https://github.com/fra589/grbl-Mega-5X
@++;  
Gauthier.

**Comment by chamnit** [comment] 2019-08-28 10:33
I can look into it. The problem is you have to be very careful about adding things to the step routine. Otherwise you will get performance hits due to the AVR being maxed out by Grbl. This manifests as struggling with keeping up with rapid gcode streams or reductions of max step rates.

**Comment by bdurbrow** [comment] 2019-08-29 00:28
I've got axis cloning for X and Y simultaneously on my fork (it's enabled with a #define directive so it doesn't have a performance hit unless you are using it); I will have dual squaring when I next get a chance to do some hacking on it. The squaring routine won't be implemented in the stepper ISR; it will be a function that takes over the machine while it's doing it's move and polls the timer instead of using the ISR.

FWIW, here's my fork:
https://github.com/bdurbrow/grbl-Mega

> reductions of max step rates

I don't quite understand _why_ yet, but that manifests as crashing when you exceed the max step rate that the ISR can keep up with... so if anybody is hacking on the ISR, and it starts crashing - perhaps intermittently - check your speed.

**Closed as completed** 2019-08-29 06:50 UTC
